accounts/urls.py
from django.urls import path
from .views import *
from accounts.views import (RegisterView, CustomLoginView, CustomPasswordChangeView, CustomPasswordResetView, CustomPasswordResetConfirmView, ProfileEditView, )
from django.contrib.auth.views import (LogoutView, )

app_name = 'accounts'

urlpatterns = [
    path('register/', RegisterView.as_view(), name = 'register'),
    path('login/', CustomLoginView.as_view(), name = 'login'),
    path('logout/', LogoutView.as_view(), name = 'logout'),
    path('change-password/', CustomPasswordChangeView.as_view(), name = 'change-password'),
    path('forget-password/', CustomPasswordResetView.as_view(), name = 'forget-password'),
    path('password-reset-confirm/<str:uidb64>/<str:token>/', CustomPasswordResetConfirmView.as_view(), name = 'password-reset-confirm'),

    path('user-profile/<int:pk>/', UserProfileView.as_view(), name = 'user-profile'),
    path('user-profile-redirect/', UserProfileRedirectView.as_view(), name = 'user-profile-redirect'),
    path('edit-profile/<int:pk>/', ProfileEditView.as_view(), name = 'edit-profile'),
]

food_stories/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


from ckeditor_uploader import views as uploader_views
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import never_cache

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('stories.urls', namespace = 'stories')),
    path('accounts/', include('accounts.urls', namespace = 'accounts')),
    path('socials/', include('allauth.urls')),

    # path('ckeditor/', include('ckeditor_uploader.urls')),

    path('ckeditor/upload/',login_required(uploader_views.upload), name='ckeditor_upload'),
    path('ckeditor/browse/', never_cache(login_required(uploader_views.browse)), name='ckeditor_browse'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stories/urls.py
from django.urls import path, include
from .views import *

from .routers import router


app_name = 'stories'

urlpatterns = [
    path('', HomePageView.as_view(), name = 'home' ),
    path('about/', about_page, name = 'about' ),
    path('contact/', ContactCreateView.as_view(), name = 'contact' ),
    path('stories/', stories_page, name = 'stories' ),
    path('recipes/', recipes_page, name = 'recipes' ),
    path('email-subscribers/', email_subscribers, name = 'email-subscribers'),
    path('single/', single, name = 'single'),


# story
    path('create-story/', StoryCreateView.as_view(), name = 'create-story'),
    path('edit-story/<int:pk>/', StoryEditView.as_view(), name = 'edit-story' ),
    path('delete-story/<int:pk>/', StoryDeleteView.as_view(), name = 'delete-story' ),
    path('story/<int:pk>/', StoryDetailView.as_view(), name = 'story-detail' ),
# subscribe
    path('subscribe/', SubscribeCreateView.as_view(), name = 'subscribe' ),
# rest-api
    path('', include(router.urls)),
]

stories/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.conf import settings
from django.urls import reverse
from django.template.defaultfilters import slugify
from accounts.models import *
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField



class Story(models.Model):
    title = models.CharField(("Title"), max_length=50)
    description = RichTextUploadingField(blank=True, null=True)
    cover = models.ImageField(_("Cover photo"), upload_to='cover/', height_field=None, width_field=None, max_length=None)

    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name=("Author"), related_name='stories', on_delete=models.CASCADE)
    category = models.ForeignKey("Category", verbose_name=("Category"), related_name='stories', on_delete=models.CASCADE)
    tag = models.ManyToManyField("Tag", verbose_name=("Tags"))

    created_at = models.DateTimeField(("Created at"), auto_now_add=True)
    updated_at = models.DateTimeField(("Updated at"), auto_now=True)

    class Meta:
        db_table = 'Story'
        verbose_name = 'Story'
        verbose_name_plural = 'Stories'

    def __str__(self):
        return f'{self.title} | {self.updated_at}'


class Recipe(models.Model):
    title = models.CharField(("Recipe name"), max_length=50)
    short_decription = models.CharField(("Short description"), max_length=250)
    description = models.TextField(("Description"))

    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name=("Author"), related_name='recipes', on_delete=models.CASCADE)
    category = models.ForeignKey("Category", verbose_name=("Category"), related_name='recipes', on_delete=models.CASCADE)
    tag = models.ManyToManyField("Tag", verbose_name=("recipes"))

    created_at = models.DateTimeField(("Created at"), auto_now_add=True)
    updated_at = models.DateTimeField(("Updated at"), auto_now=True)

    class Meta:
        db_table = 'Recipe'
        verbose_name = 'Recipe'
        verbose_name_plural = 'Recipes'

    def __str__(self):
        return f'{self.title} | {self.updated_at}'


class Category(models.Model):
    name = models.CharField(("Name"), max_length=50)
    image = models.ImageField(("Image"), upload_to=None, blank=True, null=True)

    created_at = models.DateTimeField(("Created at"), auto_now_add=True)
    updated_at = models.DateTimeField(("Updated at"), auto_now=True)

    class Meta:
        db_table = 'Category'
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    def __str__(self):
        return f'{self.name}'


class Tag(models.Model):
    name = models.CharField(("Name"), max_length=50)
    is_active = models.BooleanField(_("Active"), default=0)
    
    created_at = models.DateTimeField(("Created at"), auto_now_add=True)
    updated_at = models.DateTimeField(("Updated at"), auto_now=True)

    class Meta:
        db_table = "Tag"
        verbose_name = "Tag"
        verbose_name_plural = "Tags"

    def __str__(self):
        return f'{self.name}'


class Comment(models.Model):
    text = models.CharField(("Context"), max_length=50)

    parent = models.ForeignKey("self", verbose_name=("Reply"), related_name='children', on_delete=models.CASCADE, blank=True, null=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name=("Author"), related_name='comments', on_delete=models.CASCADE, null=True, blank=True)
    story = models.ForeignKey("Story", verbose_name=("Story"), related_name='comments', on_delete=models.CASCADE)

    created_at = models.DateTimeField(("Created at"), auto_now_add=True)
    updated_at = models.DateTimeField(("Updated at"), auto_now=True)

    class Meta:
        db_table = 'Comment'
        verbose_name = 'Comment'
        verbose_name_plural = 'Comments'

    def __str__(self):
        return f'{self.id} | {self.text} | {self.story} | {self.updated_at}'


class Subscribe(models.Model):
    email = models.EmailField(("E-mail"), max_length=254)
    
    created_at = models.DateTimeField(("Created at"), auto_now_add=True)
    updated_at = models.DateTimeField(("Updated at"), auto_now=True)

    class Meta:
        db_table = "Subscribe"
        verbose_name = "Subscriber"
        verbose_name_plural = "Subscribers"

    def __str__(self):
        return f'{self.email} | {self.updated_at}'


class Contact(models.Model):
    name = models.CharField(_("Name"), max_length=50)
    email = models.EmailField(_("E-mail"), max_length=254)
    subject = models.CharField(_("Subject"), max_length=50)
    message = models.TextField(_("Subject"))

    created_at = models.DateTimeField(("Created at"), auto_now_add=True)
    updated_at = models.DateTimeField(("Updated at"), auto_now=True)


    class Meta:
        db_table = 'Contact'
        verbose_name = _("Contact")
        verbose_name_plural = _("Contacts")

    def __str__(self):
        return f'{self.name} | {self.subject}'

stories/forms.py
from django import forms
from django.forms import modelformset_factory, inlineformset_factory, formset_factory
from stories.models import *
from ckeditor_uploader.widgets import CKEditorUploadingWidget
from ckeditor.widgets import CKEditorWidget


class ContactForm(forms.ModelForm):
    name = forms.CharField(
        widget = forms.TextInput(
            attrs={
                'placeholder' : 'Your Name',
                'class': 'form-control',
            }))
    email = forms.EmailField(
        widget = forms.EmailInput(
            attrs={
                'placeholder' : 'Your Email',
                'class': 'form-control',
            }))
    subject = forms.CharField(
        widget = forms.TextInput(
            attrs={
                'placeholder' : 'Subject',
                'class': 'form-control',
            }))
    message = forms.CharField(
        widget = forms.Textarea(
            attrs={
                'placeholder' : 'Your Message',
                'class': 'form-control',
                'cols' : '30',
                'rows' : '7',
            }))

    class Meta:
        model = Contact
        fields = ('name', 'email', 'subject', 'message', )


class SubscribeForm(forms.ModelForm):
    email = forms.EmailField(
    widget = forms.EmailInput(
        attrs={
            'placeholder' : 'Enter email address',
            'class': 'form-control',
        }))

    class Meta:
        model = Subscribe
        fields = ('email', )


class StoryForm(forms.ModelForm):
    title = forms.CharField(
        widget = forms.TextInput(
            attrs={
                'placeholder' : 'Title',
                'class': 'form-control',
            }))
    cover = forms.ImageField(label='Cover photo')
    description = forms.CharField(
        widget=CKEditorUploadingWidget(
            attrs={
                'placeholder' : 'Title',
                'class': 'form-control',
            }))

    category = forms.ModelChoiceField(
        queryset=Category.objects.all(),
        empty_label= 'Select category',
        widget = forms.Select(
            attrs={
                'class': 'form-control',
            }))
    # tag = forms.CharField(
    #     required=False,
    #     widget = forms.TextInput(
    #         attrs={
    #             'placeholder' : 'Insert your tags (seperate with " ; ")',
    #             'class': 'form-control',
    #         }))

    class Meta:
        model = Story
        fields = ('title', 'cover', 'description', 'category',  )


class CommentForm(forms.ModelForm):
    name = forms.CharField(
        required=False,
        label = 'Name',
        widget = forms.TextInput(
            attrs={
                'class': 'form-control',
            }))
    email = forms.EmailField(
        required=False,
        label = 'Email',
        widget = forms.EmailInput(
            attrs={
                'class': 'form-control',
            }))
    text = forms.CharField(
        label = 'Message',
        widget = forms.Textarea(
            attrs={
                'class': 'form-control',
                'cols' : '30',
                'rows' : '10',
            }))
    
    class Meta:
        model = Comment
        fields = ('name', 'email', 'text', )

stories/views.py
from django.shortcuts import render
from django.http import JsonResponse
from django.urls import reverse_lazy

from .models import *
from .forms import *
from .serializers import *
from .mixins import *

from accounts.models import (User,)

from django.views.generic import *
from django.views.generic.edit import (FormMixin, ModelFormMixin, )
from django.contrib.auth.mixins import (LoginRequiredMixin, )
from rest_framework.viewsets import ModelViewSet, ReadOnlyModelViewSet
from rest_framework.views import APIView






# def home_page(request):
#     context = {
#         'last_4_stories' : last_4_stories,
#         'first_3_categories' : first_3_categories,
#         'last_2_recipes' : last_2_recipes,
#         'categories' : categories,
#         'recipes' : recipes,
#         'stories' : stories,
#         'stories_count' : stories_count,
#         'recipes_count' : recipes_count,
#         'authors_count' : users_count,
#     }
#     return render(request, 'index.html', context)

def about_page(request):
    return render(request, 'about.html')

def stories_page(request):
    return render(request, 'stories.html')

def recipes_page(request):
    return render(request, 'recipes.html')


def email_subscribers(request):
    return render(request, 'email-subscribers.html')

def single(request):
    return render(request, 'single.html')


class HomePageView(TemplateView):
    template_name = "index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context = {
            'last_4_stories' : Story.objects.order_by('created_at').reverse()[:4],
            'first_3_categories' : Category.objects.order_by('created_at')[:3],
            'last_2_recipes' : Recipe.objects.order_by('created_at').reverse()[:2],
            'categories' : Category.objects.all(),
            'recipes' : Recipe.objects.all(),
            'stories' : Story.objects.all(),
            'stories_count' : Story.objects.all().count(),
            'recipes_count' : Recipe.objects.all().count(),
            'authors_count' : User.objects.all().count(),
        }
        return context
    



class ContactCreateView(CreateView):
    form_class = ContactForm
    template_name = "contact.html"
    success_url = reverse_lazy('stories:contact')


class SubscribeCreateView(CreateView):
    form_class = SubscribeForm
    http_method_names = ('post', )

    def get_success_url(self):
        return self.request.META.get('HTTP_REFERER')


class StoryCreateView(LoginRequiredMixin, CreateView):
    form_class = StoryForm
    template_name = "create_story.html"

    def get_success_url(self):
        return reverse_lazy('accounts:user-profile', kwargs={'pk': self.request.user.id})

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context['formset'] = StoryFormSet
    #     return context

    def form_valid(self, form):
        print('DDDDDDDDD', self.request.POST)
        form.instance.user = self.request.user
        form.instance.save()
        tags = self.request.POST.get('tag').split(',')
        print('CCCCCCCCC', tags)
        for tag in tags:
            tag_obj, created = Tag.objects.get_or_create(name=tag.upper())
            form.instance.tag.add(tag_obj.id)
        return super(StoryCreateView, self).form_valid(form)



class StoryEditView(LoginRequiredMixin, StoryEditMixin, UpdateView):
    model = Story
    form_class = StoryForm
    template_name = "create_story.html"
    
    def get_success_url(self):
        return reverse_lazy('accounts:user-profile', kwargs={'pk': self.request.user.id})


class StoryDeleteView(LoginRequiredMixin, StoryEditMixin, DeleteView):
    model = Story

    def get_success_url(self):
        return reverse_lazy('accounts:user-profile', kwargs={'pk': self.request.user.id})


class StoryDetailView(FormMixin, DetailView):
    model = Story
    form_class = CommentForm
    template_name = "single.html"

    def get_success_url(self):
        return reverse_lazy("stories:story-detail", kwargs={"pk": self.object.pk})

    def get_context_data(self, **kwargs):
        context = super(StoryDetailView, self).get_context_data(**kwargs)
        context["comment_form"] = self.get_form()
        context['tags'] = self.object.tag.filter(is_active=True)
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        parent_id = self.request.POST.get('parent')
        form.instance.user = self.request.user
        form.instance.story = self.get_object()
        if parent_id:
            form.instance.parent = Comment.objects.filter(id=parent_id).first()
        else:
            form.instance.parent = None
        form.save()
        return super().form_valid(form)


class TagViewSet(ModelViewSet):
    queryset = Tag.objects.all()
    serializer_class = TagSerializer
    # serializers = {
    #     'default': StorySerializer,
    #     'create': StorySerializer,
    #     'destroy': StorySerializer,
    #     'update': StorySerializer,
    #     'partial_update': StorySerializer,
    #     'list': StorySerializer,
    #     'retrieve': StorySerializer
    # }

    # def get_serializer_class(self):
    #     return self.serializers.get(self.action)

    def get_queryset(self):
        tag = self.request.GET.get('tag', '')
        try:
            obj = Tag.objects.get(name=tag)
        except:
            print('yoxdur')
        return self.queryset.filter(name__icontains=tag, is_active=True)
    

stories/templates/about.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
haqqinimizda
{% endblock title %}


{% block  body%}

<section class="hero-wrap hero-wrap-2" style="background-image: url('{% static 'images/bg_4.jpg' %}');">
    <div class="overlay"></div>
    <div class="container">
        <div class="row no-gutters slider-text align-items-end justify-content-center">
            <div class="col-md-9 ftco-animate pb-5 text-center">
                <h1 class="mb-3 bread">About Us</h1>
                <p class="breadcrumbs"><span class="mr-2"><a href="index.html">Home <i
                        class="ion-ios-arrow-forward"></i></a></span> <span>About us<i
                        class="ion-ios-arrow-forward"></i></span></p>
            </div>
        </div>
    </div>
</section>

{% endblock body %}

stories/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
{% load subscribe_tag %}

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>
        {% block title %}
        xos gelmisiz
        {% endblock title %}
    </title>

    <link href="https://fonts.googleapis.com/css?family=Poppins:200,300,400,500,600,700,900" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:400,400i,700Recipe,700i,900,900i" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'css/open-iconic-bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">

    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">

    <link rel="stylesheet" href="{% static 'css/aos.css' %}">

    <link rel="stylesheet" href="{% static 'css/ionicons.min.css' %}">

    <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'css/icomoon.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link rel="stylesheet" href="http:////netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/smoothness/jquery-ui.css">
    {% comment %} tag {% endcomment %}
    <link rel="stylesheet" href="{% static 'css/jquery.tagsinput-revisited.css' %}">

</head>
<body>

{% include 'includes/header.html' %}

{% block body %}
{% endblock body %}


{% url 'stories:home' as home_url %}
{% url 'stories:about' as about_url %}
{% if request.path == home_url or request.path == about_url %}
    {% include 'includes/about_section.html' %}
{% endif %}


{% comment %} Showing 'subscribe.html' for only '/user-profile/' url {% endcomment %}
{% url 'stories:user-profile' as user_profile_url %}
{% if request.path != user_profile_url %}
    {% subscribe_form request %}
{% endif %}

{% include 'includes/footer.html' %}

{% include 'includes/js_files.html' %}

</body>
</html>

stories/templates/create_story.html
{% extends 'base.html' %}
{% load static %}

{% url 'stories:create-story' as create_story_url %}
{% block title %}
singlesd
{% endblock title %}

{% block  body %}

<section class="ftco-section contact-section create-story">
    <div class="container">
        <div class="row block-9 justify-content-center">
            <div class="col-md-6 order-md-last d-flex">
                <form autocomplete="off" id='myform' action="{{ create_story_url }}" method='post' class="bg-light p-5 contact-form"
                    enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.non_field_errors }}
                    {{ form.errors }}
                    {{ form.media }}
                    <a class="navbar-brand center" href="#">Stories<span>.</span></a>

                    <div class="form-group">
                        {{ form.title }}
                    </div>
                    <div class="form-group">
                        {{ form.description }}
                        {{ form.description.errors }}
                    </div>
                    <div class="form-group">
                        {{ form.cover.label_tag }}
                        {{ form.cover }}
                        {{ form.cover.errors }}
                    </div>
                    <div class="form-group">
                        {{ form.category }}
                        {{ form.category.errors }}
                    </div>
                    <div class="form-group">
                        <input type="text" name="tag" placeholder="Insert your tags (seperate with &quot; ; &quot;)" class="form-control" id="id_tag" style="display: none;">
                    </div>


                    <div class="form-group">
                        {% if request.path ==  create_story_url %}
                            <input type="submit" value="Create" class="btn btn-primary py-3 px-5">
                        {% else %}
                            <input type="submit" value="Update" class="btn btn-primary py-3 px-5">
                        {% endif %}
                    </div>
                </form>

            </div>
        </div>
    </div>
</section>
{% endblock body %}

stories/templates/test.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
single
{% endblock title %}

{% block  body%}

    <section class="ftco-section contact-section create-story">
        <div class="container">
            <div class="row block-9 justify-content-center">
                <div class="col-md-6 order-md-last d-flex">
                    <form action="" method='post' class="bg-light p-5 contact-form" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.non_field_errors }}
                        {{ form.errors }}                        
                        <a class="navbar-brand center" href="#">Stories<span>.</span></a>

                        <div class="form-group">
                            {{ form.title }}
                            {{ form.title.errors }}
                        </div>
                        <div class="form-group">
                            {{ form.description }}
                            {{ form.description.errors }}
                        </div>
                        <div class="form-group">
                            {{ form.category }}
                            {{ form.category.errors }}
                        </div>
                        <div class="form-group">
                            {{ form.image }}
                            {{ form.category.errors }}
                        </div>


                        <div class="form-group">
                            {% url 'stories:create-story' as create_story_url %}
                            {% if request.path ==  create_story_url %}
                                <input type="submit" value="Create" class="btn btn-primary py-3 px-5">
                            {% else %}
                                <input type="submit" value="Update" class="btn btn-primary py-3 px-5">
                            {% endif %}
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </section>

{# 1. BUTTON TO TRIGGER THE ACTION #}
<button type="button" class="btn btn-primary js-upload-photos">
  <span class="glyphicon glyphicon-cloud-upload"></span> Upload photos
</button>

{# 2. FILE INPUT TO BE USED BY THE PLUG-IN #}
<input id="fileupload" type="file" name="image" multiple
       style="display: none;"
       data-url="{% url 'stories:test' %}"
       data-form-data='{"csrfmiddlewaretoken": "{{ csrf_token }}"}'>

{# 3. TABLE TO DISPLAY THE UPLOADED PHOTOS #}
<table id="gallery" class="table table-bordered">
  <thead>
    <tr>
      <th>Photo</th>
    </tr>
  </thead>
  <tbody>
    {% for photo in photos %}
      <tr>
        <td><a href="{{ photo.file.url }}">{{ photo.file.name }}</a></td>
      </tr>
    {% endfor %}
  </tbody>
</table>

    {% endblock body %}

stories/templates/user-profile.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
istifadeci profili
{% endblock title %}

{% block  body%}
<section class="ftco-section ftco-no-pt ">
    <div class="container">
        <div class="row">
            <div class="col-lg-3">
                <div class="user-profile-side-bar sidebar-wrap">
                    <div class="sidebar-box p-4 about text-center ftco-animate">
                        <h2 class="heading mb-4">About Me</h2>
                        <img src="{% static 'images/author.jpg' %}" class="img-fluid" alt="Colorlib Template">
                        <div class="text pt-4">
                            <p>Hi! My name is <strong>{{ object.first_name }}</strong> </p>
                            <p>{{ object.bio }}</p>
                        </div>
                    </div>
                    {% if object == user %}
                        <div class="sidebar-box ftco-animate user-profile">
                            <a href="{% url 'accounts:edit-profile' user.pk %}" class="btn btn-hover-color py-2">Edit Profile</a>
                        </div>
                        <div class="sidebar-box ftco-animate user-profile">
                            <a href="{% url 'accounts:change-password' %}" class="btn btn-hover-color py-2">Change password</a>
                        </div>
                        <div class="sidebar-box ftco-animate user-profile">
                            <a href="{% url 'stories:create-story' %}" class="btn btn-hover-color py-2">Create story </a>
                        </div>
                        <div class="sidebar-box ftco-animate user-profile">
                            <a href="single.html" class="btn btn-hover-color py-2">Create recipe </a>
                        </div>
                    {% endif %}

                    <div class="sidebar-box p-4 ftco-animate">
                        <form action="#" class="search-form">
                            <div class="form-group">
                                <span class="icon icon-search"></span>
                                <input type="text" class="form-control" placeholder="Search">
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-lg-9">
                <div class="row">
                    <div class="col-md-12 heading-section ftco-animate">
                        <h2 class="mb-4"><span>My stories and recipes</span></h2>
                    </div>
                </div>
                <div class="row">
                    {% for story in stories %}
                        <div class="col-md-4 ftco-animate">
                            <div class="blog-entry">
                                <a class="img-2">
                                    {% if object == user %}
                                        <div class="user-events__edit">
                                            <button type="button" class="edit-event"><a href="{% url 'stories:edit-story' story.pk %}"><i class="fa fa-pencil"></i></a></button>
                                            <form action="{% url 'stories:delete-story' story.pk %}" method="post">
                                                {% csrf_token %}
                                                <button type="submit" class="delete-event"><i class="fa fa-trash" aria-hidden="true"></i></button>
                                            </form>
                                        </div>
                                    {% endif %}
                                    <img src="{{ story.cover.url }}" class="img-fluid" alt="Colorlsdsdsdib Template">
                                </a>
                                <div class="text pt-3">
                                    <p class="meta d-flex"><span class="pr-3">{{ story.category }}</span><span class="ml-auto pl-3">{{ story.updated_at | date:'F d, Y' }}</span>
                                    </p>
                                    <h3><a href="{% url 'stories:story-detail' story.pk %}">{{ story.title }}</a></h3>
                                    <p class="mb-0"><a href="{% url 'stories:story-detail' story.pk %}" class="btn btn-black py-2">Read More <span
                                        class="icon-arrow_forward ml-4"></span></a></p>
                                </div>
                            </div>
                        </div>
                    {% empty %}
                        <h3>Hec bir story paylasmamisiniz..</h3>
                    {% endfor %}
                    
                </div>
            </div>


        </div>
    </div>
</section>
{% endblock body %}