accounts/urls.py
from django.urls import path
from .views import *
from accounts.views import (RegisterView, CustomLoginView, CustomPasswordChangeView, CustomPasswordResetView, CustomPasswordResetConfirmView, ProfileEditView, )
from django.contrib.auth.views import (LogoutView, )

app_name = 'accounts'

urlpatterns = [
    path('register/', RegisterView.as_view(), name = 'register'),
    path('login/', CustomLoginView.as_view(), name = 'login'),
    path('logout/', LogoutView.as_view(), name = 'logout'),
    path('change-password/', CustomPasswordChangeView.as_view(), name = 'change-password'),
    path('forget-password/', CustomPasswordResetView.as_view(), name = 'forget-password'),
    path('password-reset-confirm/<str:uidb64>/<str:token>/', CustomPasswordResetConfirmView.as_view(), name = 'password-reset-confirm'),

    path('user-profile/<int:pk>/', UserProfileView.as_view(), name = 'user-profile'),
    path('user-profile-redirect/', UserProfileRedirectView.as_view(), name = 'user-profile-redirect'),
    path('edit-profile/<int:pk>/', ProfileEditView.as_view(), name = 'edit-profile'),
]

food_stories/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


from ckeditor_uploader import views as uploader_views
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import never_cache

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('stories.urls', namespace = 'stories')),
    path('accounts/', include('accounts.urls', namespace = 'accounts')),
    path('socials/', include('allauth.urls')),

    # path('ckeditor/', include('ckeditor_uploader.urls')),

    path('ckeditor/upload/',login_required(uploader_views.upload), name='ckeditor_upload'),
    path('ckeditor/browse/', never_cache(login_required(uploader_views.browse)), name='ckeditor_browse'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stories/urls.py
from django.urls import path, include
from .views import *

from .routers import router


app_name = 'stories'

urlpatterns = [
    path('', HomePageView.as_view(), name = 'home' ),
    path('about/', about_page, name = 'about' ),
    path('contact/', ContactCreateView.as_view(), name = 'contact' ),
    path('stories/', stories_page, name = 'stories' ),
    path('recipes/', recipes_page, name = 'recipes' ),
    path('email-subscribers/', email_subscribers, name = 'email-subscribers'),
    path('single/', single, name = 'single'),


# story
    path('create-story/', StoryCreateView.as_view(), name = 'create-story'),
    path('edit-story/<int:pk>/', StoryEditView.as_view(), name = 'edit-story' ),
    path('delete-story/<int:pk>/', StoryDeleteView.as_view(), name = 'delete-story' ),
    path('story/<int:pk>/', StoryDetailView.as_view(), name = 'story-detail' ),
# subscribe
    path('subscribe/', SubscribeCreateView.as_view(), name = 'subscribe' ),
# rest-api
    path('', include(router.urls)),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.base_user import AbstractBaseUser
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager

class User(AbstractUser):
    bio = models.CharField(_("Bio"), max_length=500)
    email = models.EmailField(_('email address'), unique=True, null=True)

    class Meta:
        db_table = 'User'
        verbose_name = _("User")
        verbose_name_plural = _("Users")

accounts/forms.py
from django import forms
from accounts.models import (User, )
from django.contrib.auth.forms import (UserCreationForm, AuthenticationForm, UsernameField, PasswordChangeForm, PasswordResetForm, SetPasswordForm, )


class RegisterForm(UserCreationForm):
    first_name = forms.CharField(
        widget = forms.TextInput(
            attrs={
                'placeholder' : 'First name',
                'class' : 'form-control',
                'autofocus': 'autofocus',
            }))

    last_name = forms.CharField(
        widget = forms.TextInput(
            attrs={
                'placeholder' : 'Last name',
                'class' : 'form-control',
            }))

    username = UsernameField(
        widget = forms.TextInput(
            attrs={
                'placeholder' : 'Username',
                'class' : 'form-control',
            }))

    email = forms.EmailField(
        widget = forms.EmailInput(
            attrs={
                'placeholder' : 'Email',
                'class' : 'form-control',
            }))

    password1 = forms.CharField(
        widget = forms.PasswordInput(
            attrs={
                'placeholder' : 'Password',
                'class' : 'form-control',
            }))

    password2 = forms.CharField(
        widget = forms.PasswordInput(
            attrs={
                'placeholder' : 'Confirm password',
                'class' : 'form-control',
             }))

    class Meta:
        model = User
        fields = ('first_name', 'last_name' ,"username", 'email', 'password1', 'password2', )


class LoginForm(AuthenticationForm):
    username = UsernameField(
        widget = forms.TextInput(
            attrs={
                'placeholder' : 'Username',
                'class' : 'form-control',
            }))

    password = forms.CharField(
        widget = forms.PasswordInput(
            attrs={
                'placeholder' : 'Password',
                'class' : 'form-control',
            }))
    
    class Meta:
        model = User
        fields = ("username", 'password', )


class CustomPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(
        widget = forms.PasswordInput(
            attrs={
                'placeholder' : 'Old password',
                'class' : 'form-control',
            }))

    new_password1 = forms.CharField(
        widget = forms.PasswordInput(
            attrs={
                'placeholder' : 'New password',
                'class' : 'form-control',
            }))

    new_password2 = forms.CharField(
        widget = forms.PasswordInput(
            attrs={
                'placeholder' : 'Re-enter new password',
                'class' : 'form-control',
            }))

    class Meta:
        fields = ("old_password", 'new_password1', 'new_password2', )


class CustomPasswordResetForm(PasswordResetForm):
    email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={
                'autocomplete': 'email',
                'placeholder' : 'Email',
                'class' : 'form-control',
                }))

    class Meta:
        fields = ("email", )


class PasswordResetConfirmForm(SetPasswordForm):
    new_password1 = forms.CharField(
        widget = forms.PasswordInput(
            attrs={
                'placeholder' : 'New password',
                'class' : 'form-control',
             }))
    
    new_password2 = forms.CharField(
        widget = forms.PasswordInput(
            attrs={
                'placeholder' : 'Re-enter new password',
                'class' : 'form-control',
             }))

    class Meta:
        fields = ("new_password1", 'new_password2', )


class ProfileEditForm(forms.ModelForm):
    first_name = forms.CharField(
        label = 'Name',
        widget = forms.TextInput(
            attrs={
                'placeholder' : 'First name',
                'class' : 'form-control',
                'autofocus': 'autofocus',
            }))

    last_name = forms.CharField(
        label = 'Surname',
        widget = forms.TextInput(
            attrs={
                'placeholder' : 'Last name',
                'class' : 'form-control',
            }))

    username = UsernameField(
        label = 'Username',
        widget = forms.TextInput(
            attrs={
                'placeholder' : 'Username',
                'class' : 'form-control',
            }))

    email = forms.EmailField(
        label = 'E-mail',
        widget = forms.EmailInput(
            attrs={
                'placeholder' : 'Email',
                'class' : 'form-control',
            }))

    bio = forms.CharField(
        label = 'Bio',
        widget = forms.TextInput(
            attrs={
                'placeholder' : 'Last name',
                'class' : 'form-control',
            }))

    class Meta:
        model = User
        fields = ('first_name', 'last_name' ,"username", 'email', 'bio', )

accounts/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import *
from django.contrib.auth.views import (LoginView, PasswordChangeView, PasswordResetView, PasswordResetConfirmView, )

from .forms import *
from .models import *
from .mixins import *

from stories.models import *

from django.contrib.auth.mixins import (LoginRequiredMixin, )





class RegisterView(CreateView):
    form_class = RegisterForm
    template_name = "register.html"
    success_url = reverse_lazy('accounts:login')


class CustomLoginView(LoginView):
    form_class = LoginForm
    template_name = 'login.html'


class CustomPasswordChangeView(PasswordChangeView):
    form_class = CustomPasswordChangeForm
    template_name = "change_password.html"
    success_url = reverse_lazy('accounts:login')


class CustomPasswordResetView(PasswordResetView):
    template_name= "forget_password.html" 
    success_url = reverse_lazy('accounts:login')
    email_template_name = 'password_reset_email.html'
    form_class = CustomPasswordResetForm


class CustomPasswordResetConfirmView(PasswordResetConfirmView):
    template_name= "reset_password.html" 
    success_url = reverse_lazy('accounts:login')
    form_class = PasswordResetConfirmForm


class UserProfileView(LoginRequiredMixin,DetailView):
    model = User
    template_name = "user-profile.html"

    def get_success_url(self):
        return reverse_lazy("accounts:user-profile", kwargs={"pk": self.object.pk})

    def get_context_data(self, **kwargs):
        context = super(UserProfileView, self).get_context_data(**kwargs)
        context['user'] = self.request.user
        context['stories'] = Story.objects.filter(user=self.object.pk)
        return context



class UserProfileRedirectView(LoginRequiredMixin, RedirectView):
    def get_redirect_url(self, **kwargs):
        return reverse_lazy('accounts:user-profile', kwargs={'pk': self.request.user.id})




class ProfileEditView(LoginRequiredMixin, ProfileEditMixin, UpdateView):
    model = User
    form_class = ProfileEditForm
    template_name = "edit_profile.html"
    success_url = reverse_lazy('stories:user-profile')

accounts/templates/change_password.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
    <title>Stories - Free Bootstrap 4 Template by Colorlib</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Poppins:200,300,400,500,600,700,900" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:400,400i,700,700i,900,900i" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'css/open-iconic-bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">

    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">

    <link rel="stylesheet" href="{% static 'css/aos.css' %}">

    <link rel="stylesheet" href="{% static 'css/ionicons.min.css' %}">

    <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'css/icomoon.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark ftco-navbar-light" id="ftco-navbar">
    <div class="container">
            <a class="navbar-brand" href="{% url 'stories:home' %}">Stories<span>.</span></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="oi oi-menu"></span> Menu
        </button>

            <div class="collapse navbar-collapse" id="ftco-nav">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item active"><a href="{% url 'stories:home' %}" class="nav-link">Home</a></li>
                    <li class="nav-item"><a href="{% url 'stories:about' %}" class="nav-link">About</a></li>
                    <li class="nav-item"><a href="{% url 'stories:stories' %}" class="nav-link">Stories</a></li>
                    <li class="nav-item"><a href="{% url 'stories:recipes' %}" class="nav-link">Recipes</a></li>
                    <li class="nav-item"><a href="{% url 'stories:contact' %}" class="nav-link">Contact</a></li>
                <li><a href="" class="btn btn-black px-3 px-md-4 py-3">Sign in</a></li>
            </ul>
        </div>
    </div>
</nav>

<section class="ftco-section contact-section register">
        <div class="container">
            <div class="row block-9 justify-content-center">
                <div class="col-md-6 order-md-last d-flex">
                    <form action="" method='post' class="bg-light p-5 contact-form">
                        {% csrf_token %}
                        {{ form.non_field_errors }}
                        <div class="form-group">
                            <h4 class="reset center">Change your password</h4>
                            <h6 class="center">Please choose a new password to finish signing in.</h6>
                        </div>
                        <div class="form-group">
                            {{ form.old_password }}
                            {{ form.old_password.errors }}
                        </div>
                        <div class="form-group">
                            {{ form.new_password1 }}
                            {{ form.new_password1.errors }}
                        </div>
                        <div class="form-group">
                            {{ form.new_password2 }}
                            {{ form.new_password2.errors }}
                        </div>
                        <div class="form-group center">
                            <input type="submit" value="Change password" class="btn btn-primary py-3 px-5">
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </section>
<footer class="ftco-footer ftco-footer-2 ftco-section">
    <div class="container">
        <div class="row mb-5">
            <div class="col-md">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">Stories</h2>
                    <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there
                        live the blind texts.</p>
                    <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5">
                        <li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li>
                        <li class="ftco-animate"><a href="#"><span class="icon-facebook"></span></a></li>
                        <li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md">
                <div class="ftco-footer-widget mb-4 ml-md-5">
                    <h2 class="ftco-heading-2">Information</h2>
                    <ul class="list-unstyled">
                        <li><a href="#" class="py-2 d-block">Terms of Uses</a></li>
                        <li><a href="#" class="py-2 d-block">About Stories</a></li>
                        <li><a href="#" class="py-2 d-block">Privacy Policy</a></li>
                        <li><a href="#" class="py-2 d-block">Accessibility Help</a></li>
                        <li><a href="#" class="py-2 d-block">Advertise with us</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">Categories</h2>
                    <ul class="list-unstyled">
                        <li><a href="#" class="py-2 d-block">Food</a></li>
                        <li><a href="#" class="py-2 d-block">Restaurant</a></li>
                        <li><a href="#" class="py-2 d-passwordblock">Dessert</a></li>
                        <li><a href="#" class="py-2 d-block">Lifestyle</a></li>
                        <li><a href="#" class="py-2 d-block">Recipes</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">Have a Questions?</h2>
                    <div class="block-23 mb-3">
                        <ul>
                            <li><span class="icon icon-map-marker"></span><span class="text">203 Fake St. Mountain View, San Francisco, California, USA</span>
                            </li>
                            <li><a href="#"><span class="icon icon-phone"></span><span
                                    class="text">+2 392 3929 210</span></a></li>
                            <li><a href="#"><span class="icon icon-envelope"></span><span class="text">info@yourdomain.com</span></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 text-center">

                <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    Copyright &copy;<script>document.write(new Date().getFullYear());</script>
                    All rights reserved | This template is made with <i class="icon-heart color-danger"
                                                                        aria-hidden="true"></i> by <a
                            href="https://colorlib.com" target="_blank">Colorlib</a>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
            </div>
        </div>
    </div>
</footer>


<!-- loader -->
<div id="ftco-loader" class="show fullscreen">
    <svg class="circular" width="48px" height="48px">
        <circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/>
        <circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10"
                stroke="#F96D00"/>
    </svg>
</div>


    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/jquery-migrate-3.0.1.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
    <script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
    <script src="{% static 'js/jquery.stellar.min.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'js/aos.js' %}"></script>
    <script src="{% static 'js/jquery.animateNumber.min.js' %}"></script>
    <script src="{% static 'js/scrollax.min.js' %}"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
    <script src="{% static 'js/google-map.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>

</body>
</html>

accounts/templates/forget_password.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
    <title>Stories - Free Bootstrap 4 Template by Colorlib</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Poppins:200,300,400,500,600,700,900" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:400,400i,700,700i,900,900i" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'css/open-iconic-bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">

    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">

    <link rel="stylesheet" href="{% static 'css/aos.css' %}">

    <link rel="stylesheet" href="{% static 'css/ionicons.min.css' %}">

    <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'css/icomoon.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark ftco-navbar-light" id="ftco-navbar">
    <div class="container">
            <a class="navbar-brand" href="{% url 'stories:home' %}">Stories<span>.</span></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="oi oi-menu"></span> Menu
        </button>

            <div class="collapse navbar-collapse" id="ftco-nav">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item active"><a href="{% url 'stories:home' %}" class="nav-link">Home</a></li>
                    <li class="nav-item"><a href="{% url 'stories:about' %}" class="nav-link">About</a></li>
                    <li class="nav-item"><a href="{% url 'stories:stories' %}" class="nav-link">Stories</a></li>
                    <li class="nav-item"><a href="{% url 'stories:recipes' %}" class="nav-link">Recipes</a></li>
                    <li class="nav-item"><a href="{% url 'stories:contact' %}" class="nav-link">Contact</a></li>
                <li><a href="" class="btn btn-black px-3 px-md-4 py-3">Sign in</a></li>
            </ul>
        </div>
    </div>
</nav>
<!-- END nav -->
 <section class="ftco-section contact-section register">
        <div class="container">
            <div class="row block-9 justify-content-center">
                <div class="col-md-6 order-md-last d-flex">
                    <form action="" method='post' class="bg-light p-5 contact-form">
                        {% csrf_token %}
                        {{ form.non_field_errors }}
                        <div class="form-group">
                            <h4 class="reset center">Reset password</h4>
                            <h6 class="center">Please enter your email address to request a password reset.</h6>
                        </div>
                        <div class="form-group">
                            {{ form.email }}
                            {{ form.email.errors }}
                        </div>
                        <div class="form-group center">
                            <input type="submit" value="Reset password" class="btn btn-primary py-3 px-5">
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </section>
<footer class="ftco-footer ftco-footer-2 ftco-section">
    <div class="container">
        <div class="row mb-5">
            <div class="col-md">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">Stories</h2>
                    <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there
                        live the blind texts.</p>
                    <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5">
                        <li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li>
                        <li class="ftco-animate"><a href="#"><span class="icon-facebook"></span></a></li>
                        <li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md">
                <div class="ftco-footer-widget mb-4 ml-md-5">
                    <h2 class="ftco-heading-2">Information</h2>
                    <ul class="list-unstyled">
                        <li><a href="#" class="py-2 d-block">Terms of Uses</a></li>
                        <li><a href="#" class="py-2 d-block">About Stories</a></li>
                        <li><a href="#" class="py-2 d-block">Privacy Policy</a></li>
                        <li><a href="#" class="py-2 d-block">Accessibility Help</a></li>
                        <li><a href="#" class="py-2 d-block">Advertise with us</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">Categories</h2>
                    <ul class="list-unstyled">
                        <li><a href="#" class="py-2 d-block">Food</a></li>
                        <li><a href="#" class="py-2 d-block">Restaurant</a></li>
                        <li><a href="#" class="py-2 d-block">Dessert</a></li>
                        <li><a href="#" class="py-2 d-block">Lifestyle</a></li>
                        <li><a href="#" class="py-2 d-block">Recipes</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">Have a Questions?</h2>
                    <div class="block-23 mb-3">
                        <ul>
                            <li><span class="icon icon-map-marker"></span><span class="text">203 Fake St. Mountain View, San Francisco, California, USA</span>
                            </li>
                            <li><a href="#"><span class="icon icon-phone"></span><span
                                    class="text">+2 392 3929 210</span></a></li>
                            <li><a href="#"><span class="icon icon-envelope"></span><span class="text">info@yourdomain.com</span></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 text-center">

                <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    Copyright &copy;<script>document.write(new Date().getFullYear());</script>
                    All rights reserved | This template is made with <i class="icon-heart color-danger"
                                                                        aria-hidden="true"></i> by <a
                            href="https://colorlib.com" target="_blank">Colorlib</a>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
            </div>
        </div>
    </div>
</footer>


<!-- loader -->
<div id="ftco-loader" class="show fullscreen">
    <svg class="circular" width="48px" height="48px">
        <circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/>
        <circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10"
                stroke="#F96D00"/>
    </svg>
</div>


    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/jquery-migrate-3.0.1.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
    <script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
    <script src="{% static 'js/jquery.stellar.min.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'js/aos.js' %}"></script>
    <script src="{% static 'js/jquery.animateNumber.min.js' %}"></script>
    <script src="{% static 'js/scrollax.min.js' %}"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
    <script src="{% static 'js/google-map.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>

</body>
</html>

accounts/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% load socialaccount %}

{% block title %}
Ana sehife
{% endblock title %}

{% block  body%}

<section class="ftco-section contact-section register">
    <div class="container">
        <div class="row block-9 justify-content-center">
            <div class="col-md-6 order-md-last d-flex">
                <form action="" method='post' class="bg-light p-5 contact-form">
                    {% csrf_token %}
                    {{ form.non_field_errors }}
                    <a class="navbar-brand center" href="#">Stories<span>.</span></a>
                    <div class="form-group">
                        {{ form.username }}
                        {{ form.username.errors }}
                    </div>
                    <div class="form-group">
                        {{ form.password }}
                        {{ form.password.errors }}
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Login" class="btn btn-primary py-3 px-5">
                        <a href="{% url 'accounts:forget-password' %}" class="forgot-password">Forgot password?</a>
                    </div>
                    <div class="form-group">
                        <a href="{% url 'accounts:register' %}" class="">Don't have an account? Sign up</a>
                    </div>
        <div class="form-group center">
                        <a href="{% provider_login_url "facebook" method="oauth2" %}" class="social"><i class="fa fa-facebook social-login fb-color"></i></a>
                        <a href="{% provider_login_url "google" %}" class="social"><i class="fa fa-google-plus social-login google-color"></i></a>
                    </div>
                </form>

            </div>
        </div>
    </div>
</section>

{% endblock body %}

accounts/templates/password_reset_email.html
{% load i18n %}
{% autoescape off %}
{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}

{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}
Sifrenizi deyismek ucun bura tiklayin!
{{ protocol }}://{{ domain }}{% url 'accounts:password-reset-confirm' uidb64=uid token=token %}
{% endblock %}
{% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}

{% trans "Thanks for using our site!" %}

{% blocktrans %}The {{ site_name }} team{% endblocktrans %}

{% endautoescape %}