accounts/urls.py
from django.urls import path
from .views import *
from accounts.views import (RegisterView, CustomLoginView, CustomPasswordChangeView, CustomPasswordResetView, CustomPasswordResetConfirmView, ProfileEditView, )
from django.contrib.auth.views import (LogoutView, )

app_name = 'accounts'

urlpatterns = [
    path('register/', RegisterView.as_view(), name = 'register'),
    path('login/', CustomLoginView.as_view(), name = 'login'),
    path('logout/', LogoutView.as_view(), name = 'logout'),
    path('change-password/', CustomPasswordChangeView.as_view(), name = 'change-password'),
    path('forget-password/', CustomPasswordResetView.as_view(), name = 'forget-password'),
    path('password-reset-confirm/<str:uidb64>/<str:token>/', CustomPasswordResetConfirmView.as_view(), name = 'password-reset-confirm'),

    path('user-profile/<int:pk>/', UserProfileView.as_view(), name = 'user-profile'),
    path('user-profile-redirect/', UserProfileRedirectView.as_view(), name = 'user-profile-redirect'),
    path('edit-profile/<int:pk>/', ProfileEditView.as_view(), name = 'edit-profile'),
]

food_stories/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


from ckeditor_uploader import views as uploader_views
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import never_cache

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('stories.urls', namespace = 'stories')),
    path('accounts/', include('accounts.urls', namespace = 'accounts')),
    path('socials/', include('allauth.urls')),

    # path('ckeditor/', include('ckeditor_uploader.urls')),

    path('ckeditor/upload/',login_required(uploader_views.upload), name='ckeditor_upload'),
    path('ckeditor/browse/', never_cache(login_required(uploader_views.browse)), name='ckeditor_browse'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stories/urls.py
from django.urls import path, include
from .views import *

from .routers import router


app_name = 'stories'

urlpatterns = [
    path('', HomePageView.as_view(), name = 'home' ),
    path('about/', about_page, name = 'about' ),
    path('contact/', ContactCreateView.as_view(), name = 'contact' ),
    path('stories/', stories_page, name = 'stories' ),
    path('recipes/', recipes_page, name = 'recipes' ),
    path('email-subscribers/', email_subscribers, name = 'email-subscribers'),
    path('single/', single, name = 'single'),


# story
    path('create-story/', StoryCreateView.as_view(), name = 'create-story'),
    path('edit-story/<int:pk>/', StoryEditView.as_view(), name = 'edit-story' ),
    path('delete-story/<int:pk>/', StoryDeleteView.as_view(), name = 'delete-story' ),
    path('story/<int:pk>/', StoryDetailView.as_view(), name = 'story-detail' ),
# subscribe
    path('subscribe/', SubscribeCreateView.as_view(), name = 'subscribe' ),
# rest-api
    path('', include(router.urls)),
]

stories/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.conf import settings
from django.urls import reverse
from django.template.defaultfilters import slugify
from accounts.models import *
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField



class Story(models.Model):
    title = models.CharField(("Title"), max_length=50)
    description = RichTextUploadingField(blank=True, null=True)
    cover = models.ImageField(_("Cover photo"), upload_to='cover/', height_field=None, width_field=None, max_length=None)

    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name=("Author"), related_name='stories', on_delete=models.CASCADE)
    category = models.ForeignKey("Category", verbose_name=("Category"), related_name='stories', on_delete=models.CASCADE)
    tag = models.ManyToManyField("Tag", verbose_name=("Tags"))

    created_at = models.DateTimeField(("Created at"), auto_now_add=True)
    updated_at = models.DateTimeField(("Updated at"), auto_now=True)

    class Meta:
        db_table = 'Story'
        verbose_name = 'Story'
        verbose_name_plural = 'Stories'

    def __str__(self):
        return f'{self.title} | {self.updated_at}'


class Recipe(models.Model):
    title = models.CharField(("Recipe name"), max_length=50)
    short_decription = models.CharField(("Short description"), max_length=250)
    description = models.TextField(("Description"))

    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name=("Author"), related_name='recipes', on_delete=models.CASCADE)
    category = models.ForeignKey("Category", verbose_name=("Category"), related_name='recipes', on_delete=models.CASCADE)
    tag = models.ManyToManyField("Tag", verbose_name=("recipes"))

    created_at = models.DateTimeField(("Created at"), auto_now_add=True)
    updated_at = models.DateTimeField(("Updated at"), auto_now=True)

    class Meta:
        db_table = 'Recipe'
        verbose_name = 'Recipe'
        verbose_name_plural = 'Recipes'

    def __str__(self):
        return f'{self.title} | {self.updated_at}'


class Category(models.Model):
    name = models.CharField(("Name"), max_length=50)
    image = models.ImageField(("Image"), upload_to=None, blank=True, null=True)

    created_at = models.DateTimeField(("Created at"), auto_now_add=True)
    updated_at = models.DateTimeField(("Updated at"), auto_now=True)

    class Meta:
        db_table = 'Category'
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    def __str__(self):
        return f'{self.name}'


class Tag(models.Model):
    name = models.CharField(("Name"), max_length=50)
    is_active = models.BooleanField(_("Active"), default=0)
    
    created_at = models.DateTimeField(("Created at"), auto_now_add=True)
    updated_at = models.DateTimeField(("Updated at"), auto_now=True)

    class Meta:
        db_table = "Tag"
        verbose_name = "Tag"
        verbose_name_plural = "Tags"

    def __str__(self):
        return f'{self.name}'


class Comment(models.Model):
    text = models.CharField(("Context"), max_length=50)

    parent = models.ForeignKey("self", verbose_name=("Reply"), related_name='children', on_delete=models.CASCADE, blank=True, null=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name=("Author"), related_name='comments', on_delete=models.CASCADE, null=True, blank=True)
    story = models.ForeignKey("Story", verbose_name=("Story"), related_name='comments', on_delete=models.CASCADE)

    created_at = models.DateTimeField(("Created at"), auto_now_add=True)
    updated_at = models.DateTimeField(("Updated at"), auto_now=True)

    class Meta:
        db_table = 'Comment'
        verbose_name = 'Comment'
        verbose_name_plural = 'Comments'

    def __str__(self):
        return f'{self.id} | {self.text} | {self.story} | {self.updated_at}'


class Subscribe(models.Model):
    email = models.EmailField(("E-mail"), max_length=254)
    
    created_at = models.DateTimeField(("Created at"), auto_now_add=True)
    updated_at = models.DateTimeField(("Updated at"), auto_now=True)

    class Meta:
        db_table = "Subscribe"
        verbose_name = "Subscriber"
        verbose_name_plural = "Subscribers"

    def __str__(self):
        return f'{self.email} | {self.updated_at}'


class Contact(models.Model):
    name = models.CharField(_("Name"), max_length=50)
    email = models.EmailField(_("E-mail"), max_length=254)
    subject = models.CharField(_("Subject"), max_length=50)
    message = models.TextField(_("Subject"))

    created_at = models.DateTimeField(("Created at"), auto_now_add=True)
    updated_at = models.DateTimeField(("Updated at"), auto_now=True)


    class Meta:
        db_table = 'Contact'
        verbose_name = _("Contact")
        verbose_name_plural = _("Contacts")

    def __str__(self):
        return f'{self.name} | {self.subject}'

stories/forms.py
from django import forms
from django.forms import modelformset_factory, inlineformset_factory, formset_factory
from stories.models import *
from ckeditor_uploader.widgets import CKEditorUploadingWidget
from ckeditor.widgets import CKEditorWidget


class ContactForm(forms.ModelForm):
    name = forms.CharField(
        widget = forms.TextInput(
            attrs={
                'placeholder' : 'Your Name',
                'class': 'form-control',
            }))
    email = forms.EmailField(
        widget = forms.EmailInput(
            attrs={
                'placeholder' : 'Your Email',
                'class': 'form-control',
            }))
    subject = forms.CharField(
        widget = forms.TextInput(
            attrs={
                'placeholder' : 'Subject',
                'class': 'form-control',
            }))
    message = forms.CharField(
        widget = forms.Textarea(
            attrs={
                'placeholder' : 'Your Message',
                'class': 'form-control',
                'cols' : '30',
                'rows' : '7',
            }))

    class Meta:
        model = Contact
        fields = ('name', 'email', 'subject', 'message', )


class SubscribeForm(forms.ModelForm):
    email = forms.EmailField(
    widget = forms.EmailInput(
        attrs={
            'placeholder' : 'Enter email address',
            'class': 'form-control',
        }))

    class Meta:
        model = Subscribe
        fields = ('email', )


class StoryForm(forms.ModelForm):
    title = forms.CharField(
        widget = forms.TextInput(
            attrs={
                'placeholder' : 'Title',
                'class': 'form-control',
            }))
    cover = forms.ImageField(label='Cover photo')
    description = forms.CharField(
        widget=CKEditorUploadingWidget(
            attrs={
                'placeholder' : 'Title',
                'class': 'form-control',
            }))

    category = forms.ModelChoiceField(
        queryset=Category.objects.all(),
        empty_label= 'Select category',
        widget = forms.Select(
            attrs={
                'class': 'form-control',
            }))
    # tag = forms.CharField(
    #     required=False,
    #     widget = forms.TextInput(
    #         attrs={
    #             'placeholder' : 'Insert your tags (seperate with " ; ")',
    #             'class': 'form-control',
    #         }))

    class Meta:
        model = Story
        fields = ('title', 'cover', 'description', 'category',  )


class CommentForm(forms.ModelForm):
    name = forms.CharField(
        required=False,
        label = 'Name',
        widget = forms.TextInput(
            attrs={
                'class': 'form-control',
            }))
    email = forms.EmailField(
        required=False,
        label = 'Email',
        widget = forms.EmailInput(
            attrs={
                'class': 'form-control',
            }))
    text = forms.CharField(
        label = 'Message',
        widget = forms.Textarea(
            attrs={
                'class': 'form-control',
                'cols' : '30',
                'rows' : '10',
            }))
    
    class Meta:
        model = Comment
        fields = ('name', 'email', 'text', )

stories/views.py
from django.shortcuts import render
from django.http import JsonResponse
from django.urls import reverse_lazy

from .models import *
from .forms import *
from .serializers import *
from .mixins import *

from accounts.models import (User,)

from django.views.generic import *
from django.views.generic.edit import (FormMixin, ModelFormMixin, )
from django.contrib.auth.mixins import (LoginRequiredMixin, )
from rest_framework.viewsets import ModelViewSet, ReadOnlyModelViewSet
from rest_framework.views import APIView






# def home_page(request):
#     context = {
#         'last_4_stories' : last_4_stories,
#         'first_3_categories' : first_3_categories,
#         'last_2_recipes' : last_2_recipes,
#         'categories' : categories,
#         'recipes' : recipes,
#         'stories' : stories,
#         'stories_count' : stories_count,
#         'recipes_count' : recipes_count,
#         'authors_count' : users_count,
#     }
#     return render(request, 'index.html', context)

def about_page(request):
    return render(request, 'about.html')

def stories_page(request):
    return render(request, 'stories.html')

def recipes_page(request):
    return render(request, 'recipes.html')


def email_subscribers(request):
    return render(request, 'email-subscribers.html')

def single(request):
    return render(request, 'single.html')


class HomePageView(TemplateView):
    template_name = "index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context = {
            'last_4_stories' : Story.objects.order_by('created_at').reverse()[:4],
            'first_3_categories' : Category.objects.order_by('created_at')[:3],
            'last_2_recipes' : Recipe.objects.order_by('created_at').reverse()[:2],
            'categories' : Category.objects.all(),
            'recipes' : Recipe.objects.all(),
            'stories' : Story.objects.all(),
            'stories_count' : Story.objects.all().count(),
            'recipes_count' : Recipe.objects.all().count(),
            'authors_count' : User.objects.all().count(),
        }
        return context
    



class ContactCreateView(CreateView):
    form_class = ContactForm
    template_name = "contact.html"
    success_url = reverse_lazy('stories:contact')


class SubscribeCreateView(CreateView):
    form_class = SubscribeForm
    http_method_names = ('post', )

    def get_success_url(self):
        return self.request.META.get('HTTP_REFERER')


class StoryCreateView(LoginRequiredMixin, CreateView):
    form_class = StoryForm
    template_name = "create_story.html"

    def get_success_url(self):
        return reverse_lazy('accounts:user-profile', kwargs={'pk': self.request.user.id})

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context['formset'] = StoryFormSet
    #     return context

    def form_valid(self, form):
        print('DDDDDDDDD', self.request.POST)
        form.instance.user = self.request.user
        form.instance.save()
        tags = self.request.POST.get('tag').split(',')
        print('CCCCCCCCC', tags)
        for tag in tags:
            tag_obj, created = Tag.objects.get_or_create(name=tag.upper())
            form.instance.tag.add(tag_obj.id)
        return super(StoryCreateView, self).form_valid(form)



class StoryEditView(LoginRequiredMixin, StoryEditMixin, UpdateView):
    model = Story
    form_class = StoryForm
    template_name = "create_story.html"
    
    def get_success_url(self):
        return reverse_lazy('accounts:user-profile', kwargs={'pk': self.request.user.id})


class StoryDeleteView(LoginRequiredMixin, StoryEditMixin, DeleteView):
    model = Story

    def get_success_url(self):
        return reverse_lazy('accounts:user-profile', kwargs={'pk': self.request.user.id})


class StoryDetailView(FormMixin, DetailView):
    model = Story
    form_class = CommentForm
    template_name = "single.html"

    def get_success_url(self):
        return reverse_lazy("stories:story-detail", kwargs={"pk": self.object.pk})

    def get_context_data(self, **kwargs):
        context = super(StoryDetailView, self).get_context_data(**kwargs)
        context["comment_form"] = self.get_form()
        context['tags'] = self.object.tag.filter(is_active=True)
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        parent_id = self.request.POST.get('parent')
        form.instance.user = self.request.user
        form.instance.story = self.get_object()
        if parent_id:
            form.instance.parent = Comment.objects.filter(id=parent_id).first()
        else:
            form.instance.parent = None
        form.save()
        return super().form_valid(form)


class TagViewSet(ModelViewSet):
    queryset = Tag.objects.all()
    serializer_class = TagSerializer
    # serializers = {
    #     'default': StorySerializer,
    #     'create': StorySerializer,
    #     'destroy': StorySerializer,
    #     'update': StorySerializer,
    #     'partial_update': StorySerializer,
    #     'list': StorySerializer,
    #     'retrieve': StorySerializer
    # }

    # def get_serializer_class(self):
    #     return self.serializers.get(self.action)

    def get_queryset(self):
        tag = self.request.GET.get('tag', '')
        try:
            obj = Tag.objects.get(name=tag)
        except:
            print('yoxdur')
        return self.queryset.filter(name__icontains=tag, is_active=True)
    

stories/templates/includes/about_section.html
{% load static %} 

<section class="ftco-counter ftco-section ftco-no-pt ftco-no-pb img" id="section-counter">
    <div class="container">
        <div class="row d-flex">
            <div class="col-md-6 d-flex">
                <div class="img d-flex align-self-stretch" style="background-image:url({% static 'images/about.jpg' %});"></div>
            </div>
            <div class="col-md-6 pl-md-5 py-5">
                <div class="row justify-content-start pb-3">
                    <div class="col-md-12 heading-section ftco-animate">
                        <h2 class="mb-4"><span>About Stories</span></h2>
                        <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia</p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6 justify-content-center counter-wrap ftco-animate">
                        <div class="block-18 text-center py-5 bg-light mb-4">
                            <div class="text">
                                <strong class="number" data-number="6"></strong>
                                <span>Daily visitors</span>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6 justify-content-center counter-wrap ftco-animate">
                        <div class="block-18 text-center py-5 bg-light mb-4">
                            <div class="text">
                                <strong class="number" data-number="200">0</strong>
                                <span>Stories</span>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6 justify-content-center counter-wrap ftco-animate">
                        <div class="block-18 text-center py-5 bg-light mb-4">
                            <div class="text">
                                <strong class="number" data-number="300">0</strong>
                                <span>Recipes</span>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6 justify-content-center counter-wrap ftco-animate">
                        <div class="block-18 text-center py-5 bg-light mb-4">
                            <div class="text">
                                <strong class="number" data-number="40">0</strong>
                                <span>Users</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

stories/templates/includes/comment.html
{% load static %}


<li class="comment" id='comment_id_{{ comment.id }}'>
    <div class="vcard bio">
        <img src="{% static 'images/person_1.jpg' %}" alt="Image placeholder">
    </div>
    <div class="comment-body">
        <h3>{{ comment.user.first_name }} {{ comment.user.last_name }}
        </h3>
        <div class="meta">{{ comment.updated_at }}</div>
        <p>{{ comment.text }}</p>
        <!-- <a><a href="" class="reply">Reply</a></p> -->
        <button class='comment_reply' id="comment_id_{{ comment.id  }}">Reply</button>
    </div>
    <div id="comment_wrapper_{{ comment.id }}" class="comment_wrapper"></div>
    {% if comment.children %}
        {% for comment in comment.children.all %}
        <ul class="children">
            {% include 'includes/comment.html' %}
        </ul>
        {% endfor %}
    {% endif %}
</li>

stories/templates/includes/footer.html
{% load static %} 

    <footer class="ftco-footer ftco-footer-2 ftco-section">
        <div class="container">
            <div class="row mb-5">
                <div class="col-md">
                    <div class="ftco-footer-widget mb-4">
                        <h2 class="ftco-heading-2">Stories</h2>
                        <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
                        <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5">
                            <li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li>
                            <li class="ftco-animate"><a href="#"><span class="icon-facebook"></span></a></li>
                            <li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-md">
                    <div class="ftco-footer-widget mb-4 ml-md-5">
                        <h2 class="ftco-heading-2">Information</h2>
                        <ul class="list-unstyled">
                            <li><a href="#" class="py-2 d-block">Terms of Uses</a></li>
                            <li><a href="#" class="py-2 d-block">About Stories</a></li>
                            <li><a href="#" class="py-2 d-block">Privacy Policy</a></li>
                            <li><a href="#" class="py-2 d-block">Accessibility Help</a></li>
                            <li><a href="#" class="py-2 d-block">Advertise with us</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-md">
                    <div class="ftco-footer-widget mb-4">
                        <h2 class="ftco-heading-2">Categories</h2>
                        <ul class="list-unstyled">
                            {% for category in categories %}
                                <li><a href="#" class="py-2 d-block">{{ category.name }}</a></li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
                <div class="col-md">
                    <div class="ftco-footer-widget mb-4">
                        <h2 class="ftco-heading-2">Have a Questions?</h2>
                        <div class="block-23 mb-3">
                            <ul>
                                <li><span class="icon icon-map-marker"></span><span class="text">203 Fake St. Mountain View, San Francisco, California, USA</span>
                                </li>
                                <li><a href="#"><span class="icon icon-phone"></span><span
                                    class="text">+2 392 3929 210</span></a></li>
                                <li><a href="#"><span class="icon icon-envelope"></span><span class="text">info@yourdomain.com</span></a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12 text-center">

                    <p>
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        Copyright &copy;
                        <script>
                            document.write(new Date().getFullYear());
                        </script>
                        All rights reserved | This template is made with <i class="icon-heart color-danger" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    </p>
                </div>
            </div>
        </div>
    </footer>


    <!-- loader -->
    <div id="ftco-loader" class="show fullscreen">
        <svg class="circular" width="48px" height="48px">
        <circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/>
        <circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10"
                stroke="#F96D00"/>
    </svg>
    </div>

stories/templates/includes/header.html
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark ftco-navbar-light" id="ftco-navbar">
        <div class="container">
            <a class="navbar-brand" href="{% url 'stories:home' %}">Stories<span>.</span></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="oi oi-menu"></span> Menu
        </button>

            <div class="collapse navbar-collapse" id="ftco-nav">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item active"><a href="{% url 'stories:home' %}" class="nav-link">Home</a></li>
                    <li class="nav-item"><a href="{% url 'stories:about' %}" class="nav-link">About</a></li>
                    <li class="nav-item"><a href="{% url 'stories:stories' %}" class="nav-link">Stories</a></li>
                    <li class="nav-item"><a href="{% url 'stories:recipes' %}" class="nav-link">Recipes</a></li>
                    <li class="nav-item"><a href="{% url 'stories:contact' %}" class="nav-link">Contact</a></li>

                    {% if user.is_authenticated %}
                        <li class="nav-item"><a href="{% url 'accounts:user-profile' user.pk %}" class="nav-link">{{ user.first_name }}</a></li>
                        <li><a href="{% url 'accounts:logout' %}" class="btn btn-black px-3 px-md-4 py-3">Log out</a></li>
                    {% else %}
                        <li><a href="{% url 'accounts:login' %}" class="btn btn-black px-3 px-md-4 py-3">Sign in</a></li>
                    {% endif %}
                    
                </ul>
            </div>
        </div>
    </nav>

stories/templates/includes/js_files.html
 {% load static %} 
 
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/jquery-migrate-3.0.1.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
    <script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
    <script src="{% static 'js/jquery.stellar.min.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'js/aos.js' %}"></script>
    <script src="{% static 'js/jquery.animateNumber.min.js' %}"></script>
    <script src="{% static 'js/scrollax.min.js' %}"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
    <script src="{% static 'js/google-map.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>

  <script src="//code.jquery.com/jquery-1.12.4.js"></script>
  <script src="//code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

 {% comment %} tag {% endcomment %}
 <script src="{% static 'js/jquery.tagsinput-revisited.js' %}"></script>

 {% comment %} <script src="{% static 'js/asd/vendor/jquery.ui.widget.js' %}"></script>
  <script src="{% static 'js/asd/jquery.iframe-transport.js' %}"></script>
  <script src="{% static 'js/asd/jquery.fileupload.js' %}"></script> {% endcomment %}

  <script src="https://cdnjs.cloudflare.com/ajax/libs/reconnecting-websocket/1.0.0/reconnecting-websocket.min.js"></script>
  <script src="{% static 'js/app.js' %}"></script>

stories/templates/includes/subscribe.html
    <section class="ftco-subscribe ftco-section bg-light">
        <div class="overlay">
            <div class="container">
                <div class="row d-flex justify-content-center">
                    <div class="col-md-8 text-wrap text-center heading-section ftco-animate">
                        <h2 class="mb-4"><span>Subcribe to our Newsletter</span></h2>
                        <p>A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth.</p>
                        <div class="row d-flex justify-content-center mt-4 mb-4">
                            <div class="col-md-8">
                                <form action="{% url 'stories:subscribe' %}" method='post' class="subscribe-form">
                                    {% csrf_token %}
                                    <div class="form-group d-flex">
                                        {{ form.email }}
                                        {{ form.email.errors }}
                                        <input type="submit" value="Subscribe" class="submit px-3">
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>#